server:
  port: 8082
spring:
  application:
    name: boot-eureka-order
  datasource:
#     url: jdbc:mysql://127.0.0.1:3306/demo?characterEncoding=utf-8&useSSL=true
#     username: root
#     password: root
#     driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:
  h2: # 使用H2 控制台   访问页面http://localhost:8080/h2-console/，默认的数据库为jdbc:h2:mem:testdb
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update  
